version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - DB_USER="postgres2" 
      - DB_PASSWORD="123456"
      - DB_NAME="pantry_dash"
      - DB_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres2"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "pantry_dash"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./server/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db-data:
