version: "3.8"
services:
  client:
    build:
      context: ./client
      args:
        - REACT_APP_DB_SERVER=${PG_SERVER}
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    environment:
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_NAME=${PG_NAME}
      - DB_HOST=db
      - DB_SERVER=${PG_SERVER}
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
