version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - REACT_APP_DB_SERVER=${PG_SERVER}
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_NAME=${PG_NAME}
      - DB_HOST=db
      - DB_SERVER=${PG_SERVER}
    ports:
      - "5000:5000"
    depends_on:
      - db


  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}" 
      POSTGRES_DB: "${PG_NAME}"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./server/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db-data:
